/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411ce.h"
#include "gpio_driver.h"
//#include <../drivers/Inc/gpio_driver.h>
int main(void)
{
	GpioHandle *gpio;
	gpio->X = GPIOD;
	gpio->Config.Mode = OUTPUT;
	gpio->Config.Pin = 12;


	 InitGpio(gpio);

    /* Loop forever */
	for(;;);
	TurnOn(gpio);
}
